#!/usr/bin/env bash
# PostgreSQL ~ S3 구간 이벤트 유실 감사 실행기.
#
#   ./audit/run_audit.sh <RUN_ID>
#
# <RUN_ID> 는 k6/run.sh cdc_audit 가 만든 결과 파일의 접미사다.
#   k6/results/cdc_audit-<RUN_ID>.ndjson  감사 키
#   k6/results/cdc_audit-<RUN_ID>.json    k6 요약 (sql_errors 게이트용)
#
# 선행 조건: 부하 종료 -> rotate.interval.ms + 여유 대기 -> k6/sql/flush.sql 실행.
# 센티널로 마지막 파일을 닫지 않으면 끝부분이 버퍼에 남아 유실로 오판된다.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

RUN_ID="${1:-}"
if [ -z "${RUN_ID}" ]; then
    echo "usage: $0 <RUN_ID>" >&2
    exit 2
fi

for cmd in duckdb jq; do
    command -v "${cmd}" >/dev/null 2>&1 || { echo "FATAL: ${cmd} not found in PATH" >&2; exit 1; }
done

ENV_FILE="${ENV_FILE:-${REPO_ROOT}/infra/.env}"
if [ -f "${ENV_FILE}" ]; then
    set -a
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    set +a
fi

: "${S3_BUCKET:?S3_BUCKET is required (set it in infra/.env)}"
: "${TOPIC_PREFIX:?TOPIC_PREFIX is required (set it in infra/.env)}"
# topics.dir 과 같은 값이어야 한다. 끝 슬래시는 떼어 s3:// 경로에 // 가 생기지 않게 한다.
S3_PREFIX="${S3_PREFIX:-cdc/}"
S3_PREFIX="${S3_PREFIX%/}"

RESULTS_DIR="${REPO_ROOT}/k6/results"
NDJSON_RAW="${RESULTS_DIR}/cdc_audit-${RUN_ID}.ndjson"
SUMMARY="${RESULTS_DIR}/cdc_audit-${RUN_ID}.json"

WORK_DIR="${RESULTS_DIR}/audit-${RUN_ID}"
EVENTS="${WORK_DIR}/events.ndjson"
SOURCES="${WORK_DIR}/_sources.sql"

[ -f "${NDJSON_RAW}" ] || { echo "FATAL: ${NDJSON_RAW} not found" >&2; exit 1; }
[ -f "${SUMMARY}" ]    || { echo "FATAL: ${SUMMARY} not found" >&2; exit 1; }

# k6~PostgreSQL 구간의 에러는 감사를 무효화하지 않는다. 에러가 난 문장은 k6 가 기록하지
# 않았고, 기록하지 않은 이벤트는 검증 대상이 아니다. 다만 에러가 많으면 그만큼 검증 범위가
# 줄어드니 참고용으로 같이 찍는다.
SQL_ERRORS="$(jq -r '.metrics.sql_errors.count // 0' "${SUMMARY}")"
ITERATIONS="$(jq -r '.metrics.iterations.count // 0' "${SUMMARY}")"

# ── 입력 준비 ─────────────────────────────────────────────────────────────
mkdir -p "${WORK_DIR}"

# --console-output 파일에는 setup() 의 로그 같은 비 JSON 줄도 섞인다. 접두어로 거른다.
grep '^@@' "${NDJSON_RAW}" | cut -c3- > "${EVENTS}"
EVENT_LINES="$(wc -l < "${EVENTS}")"
if [ "${EVENT_LINES}" -eq 0 ]; then
    echo "FATAL: no audit keys in ${NDJSON_RAW}" >&2
    echo "was the run started with run.sh cdc_audit (which sets --console-output)?" >&2
    exit 1
fi

# 경로만 담은 생성 파일. audit.sql 은 소스를 모르고 뷰 이름만 쓴다.
# 로컬에 내려받은 parquet 으로 돌리려면 이 파일의 s3:// 를 로컬 경로로 바꾸면 된다.
{
    echo "-- generated by run_audit.sh for RUN_ID=${RUN_ID}. do not edit."
    echo
    printf "CREATE OR REPLACE VIEW raw_k6 AS\n"
    printf "SELECT * FROM read_json('%s',\n" "${EVENTS}"
    printf "                        format = 'newline_delimited',\n"
    printf "                        columns = {t: 'VARCHAR', k: 'VARCHAR', e: 'VARCHAR'});\n"
    echo
    # 감사 대상 트래픽이 닿는 토픽만 읽는다. users 와 merchants 는 감사 부하가 건드리지 않는다.
    for table in products transactions transaction_items; do
        printf "CREATE OR REPLACE VIEW raw_%s AS\n" "${table}"
        printf "SELECT * FROM read_parquet('s3://%s/%s/%s.public.%s/**/*.parquet',\n" \
            "${S3_BUCKET}" "${S3_PREFIX}" "${TOPIC_PREFIX}" "${table}"
        printf "                           union_by_name = true);\n"
        echo
    done
} > "${SOURCES}"

echo "run_id=${RUN_ID} iterations=${ITERATIONS} sql_errors=${SQL_ERRORS} audit_keys=${EVENT_LINES}" >&2
echo "s3=s3://${S3_BUCKET}/${S3_PREFIX}/" >&2
echo >&2

# 영속 DB 를 만들지 않는다. -init /dev/null 로 ~/.duckdbrc 자동 로딩을 끄고
# 세션 설정은 init.sql 에만 둔다. 그래야 돌리는 사람의 홈 디렉터리와 무관하게 재현된다.
cat "${SCRIPT_DIR}/duckdb/init.sql" "${SOURCES}" "${SCRIPT_DIR}/duckdb/audit.sql" \
    | duckdb -init /dev/null
